[theme]
primaryColor = "#FFC630"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#141414"
font = "sans serif"

[server]
headless = true
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false
